vim.keymap.set("n", "<C-T>", vim.cmd.FloatermToggle)
vim.keymap.set("t", "<C-T>", vim.cmd.FloatermHide)
vim.keymap.set("t", "<C-Q>", vim.cmd.FloatermKill)
vim.keymap.set("t", "<C-N>", vim.cmd.FloatermNew)
vim.keymap.set("t", "<C-H>", vim.cmd.FloatermPrev)
vim.keymap.set("t", "<C-L>", vim.cmd.FloatermNext)
